### ISSUE TITLE
[BUG][SDCARD] Sometimes external sdcard  will not show on settings

### ISSUE THREAD

**Issue by urain39** [washinson/android_device_meizu_meilan3#2]
Sometimes external sdcard  will not show on settings, even though it is have mounted at /mnt/media_rw/sdcard1.

**Comment by washinson** [comment]
What does sometimes mean? Does it happen randomly or after something?

**Comment by urain39** [comment]
@washinson Seems to only happen when the device is rebooted(randomly, i'm not pretty sure).

**Comment by urain39** [comment]
By the way, can you re-add(enable) ZRAM in init.rc?

**Comment by washinson** [comment]
Ok i will try to check this problem
I can add zram but i think that performance will lose.

**Comment by urain39** [comment]
Thanks a lot!

**Comment by washinson** [comment]
I rebooted 3 times and sdcard loaded normally in settings. I pushed supposed solution https://github.com/washinson/android_device_meizu_m3_m3s-common/commit/87c11dd368b84765799edef5b384869f9cc23fbe

**Comment by urain39** [comment]
I just searched in github, looks like it is not related codes. I think i need some time to wait it occurs again.

**Comment by urain39** [comment]
I tried many times too, no recurrent now. I started think that may be my misoperation..

**Comment by washinson** [comment]
¯\_(ツ)_/¯
Reopen if it will repeat
